# Generated by Django 4.2.2 on 2023-07-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_blocked_user_profile_blocked_profile'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='down',
            field=models.ManyToManyField(blank=True, null=True, related_name='downpost', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='up',
            field=models.ManyToManyField(blank=True, null=True, related_name='upost', to='accounts.profile'),
        ),
    ]
