# Generated by Django 4.2.2 on 2023-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'female'), ('m', 'male')], max_length=6, null=True),
        ),
    ]
