# Generated by Django 4.2.2 on 2023-07-01 17:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('accounts', '0003_tag_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
