# Generated by Django 4.2.2 on 2023-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_tag_alter_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexpandeducation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexpandeducation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
