# Generated by Django 4.2.2 on 2023-07-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_workexpandeducation_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languge',
        ),
    ]
