# Generated by Django 4.2.2 on 2023-07-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_languge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languge',
        ),
    ]
