# Generated by Django 4.2.2 on 2023-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_languge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languge',
            name='language',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
    ]
