# Generated by Django 4.2.2 on 2023-07-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_languge_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blocked_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_Profile',
            field=models.ManyToManyField(blank=True, related_name='bloced_by', to='accounts.profile'),
        ),
    ]
