# Generated by Django 4.2.2 on 2023-07-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_blocked_user_profile_blocked_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexpandeducation',
            name='InstituteType',
            field=models.CharField(choices=[('school', 'School'), ('collage', 'Collage'), ('institute', 'Institute'), ('company', 'Company')], default='School', max_length=9),
        ),
    ]
