# Generated by Django 4.2.2 on 2023-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_languge_listing_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languge',
            name='listing_level',
            field=models.CharField(choices=[('A1', 1), ('A2', 2), ('B1', 3), ('B2', 4), ('C1', 5), ('C2', 6)], max_length=2),
        ),
        migrations.AlterField(
            model_name='languge',
            name='reading_level',
            field=models.CharField(choices=[('A1', 1), ('A2', 2), ('B1', 3), ('B2', 4), ('C1', 5), ('C2', 6)], max_length=2),
        ),
        migrations.AlterField(
            model_name='languge',
            name='writing_level',
            field=models.CharField(choices=[('A1', 1), ('A2', 2), ('B1', 3), ('B2', 4), ('C1', 5), ('C2', 6)], max_length=2),
        ),
    ]
