# Generated by Django 4.2.2 on 2023-07-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_languge_listing_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languge',
            name='listing_level',
            field=models.CharField(choices=[('1', 'A1'), ('2', 'A2'), ('3', 'B1'), ('4', 'B2'), ('5', 'C1'), ('6', 'C2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='languge',
            name='reading_level',
            field=models.CharField(choices=[('1', 'A1'), ('2', 'A2'), ('3', 'B1'), ('4', 'B2'), ('5', 'C1'), ('6', 'C2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='languge',
            name='writing_level',
            field=models.CharField(choices=[('1', 'A1'), ('2', 'A2'), ('3', 'B1'), ('4', 'B2'), ('5', 'C1'), ('6', 'C2')], max_length=2),
        ),
    ]
